# Generated by Django 4.2.5 on 2023-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trashData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.TimeField(default='00:00:00')),
                ('dustbin_id', models.IntegerField(max_length=5, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('perc', models.IntegerField(max_length=5, null=True)),
            ],
        ),
    ]
